# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps: 
      - uses: actions/checkout@v2
      - name: Build with the latest action rev
        uses: tsg-iitkgp/next-build-export-action@v1.1
        env:
          BUILD_DIR: .
          PAGES_BRANCH: docs
          TOKEN: ${{ secrets.TOKEN }}
